version: "3"

services:
  jellyfin:
    image: jellyfin/jellyfin
    volumes:
      - config:/config:z
      - ./videos:/media/videos:ro
      - ${PWD}/JellyfinJav/bin/Debug/netstandard2.1/JellyfinJav.dll:/config/plugins/JellyfinJav.dll:ro
    ports:
      - 127.0.0.1:8896:8096

volumes:
  config:
